---
- name: Deploy CyberChef
  hosts: cyberchef
  become: true

  tasks:
    - name: Install Docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - git
        state: present
        update_cache: true

    - name: Add Docker repository
      deb822_repository:
        name: docker
        types: deb
        uris: https://download.docker.com/linux/ubuntu
        suites: noble
        components: stable
        architectures: amd64
        signed_by: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: true

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Clone CyberChef-server
      ansible.builtin.git:
        repo: https://github.com/gchq/CyberChef-server.git
        dest: /opt/cyberchef-server
        version: v1.1.0

    - name: Build CyberChef-server image
      community.docker.docker_image:
        name: cyberchef-server
        tag: v1.1.0
        source: build
        build:
          path: /opt/cyberchef-server

    - name: Run CyberChef-server container
      community.docker.docker_container:
        name: cyberchef
        image: cyberchef-server:v1.1.0
        state: started
        restart_policy: always
        ports:
          - "3000:3000"