---
- name: Deploy CyberChef
  hosts: cyberchef
  become: true

  tasks:
    - name: Install Docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: true

    - name: Add Docker repository
      deb822_repository:
        name: docker
        types: deb
        uris: https://download.docker.com/linux/ubuntu
        suites: noble
        components: stable
        architectures: amd64
        signed_by: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: true

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Run CyberChef container
      community.docker.docker_container:
        name: cyberchef
        image: mpepping/cyberchef
        state: started
        restart_policy: always
        ports:
          - "3000:80"